name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: make test

    - name: Build
      run: make build
